### ISSUE TITLE
Request to Rename Project Due to Unintended Offensive Connotation

### ISSUE THREAD

**Issue by munabedan** [munabedan/incul-manager#2]
Hello everyone,

I am writing to address an important matter regarding the name of the project, "Incul Manager". It has come to my attention that the name may have unintended offensive connotations, particularly in Italian, where "incul" is a slang term with inappropriate and vulgar associations.

I want to sincerely apologize to anyone who may have been offended by the name. The intention behind the project name was never to cause harm or discomfort, and I deeply regret any negative impact it may have had.

To address this concern, I will be renaming the project. The original name was intended to reflect the underlying technology, Incus without inflicting on their branding. However, I now realize that the current name is not appropriate, and I will be selecting a new name that is more respectful and considerate of multiple cultural contexts.

If you have any suggestions for a new name or feedback on this matter, please don't hesitate to reach out.

Thank you for your understanding,

**Comment by RubensRainelli** [comment]
m2c:
Leave that name... It's not a drama at all for Italians. And incul has no meaning. It's inculare that means:
steal, fuck in the arse, take joke of someone stealing the business.

But really, take the name. It's funny, not terrible because the wording is not a really bad one but a joking one, let's say that if you say 🦆 in English, it's stronger that inculare.

This word is quite of common use and having a funny and simple name to remember, is a really good thing.

**Comment by munabedan** [comment]
Hello everyone,

After thoughtful consideration and discussions with the Italian community, I've decided to keep the project name "Incul Manager." While there were concerns around connotations in Italian, I've been reassured that it’s not offensive in context. 

I've also learned there's potential for humor (as risqué as it might be) due to the unintended bilingual pun, which many in the Italian community found funny and memorable.

Thank you to everyone who shared feedback. I appreciate the supportive and constructive responses!
